services:
  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq2
    ports:
      - "5672:5672"
      - "15672:15672"
    tty: true
    restart: unless-stopped

  vendas-estoque:
    build: .

      